Fix toggling all checkboxes of failed imports
mouse-reeve/bookwyrm pull request #696
Opened 2021-03-05 15:42 UTC by arkhi

Currently, Checking all boxes is kind of funky:

https://user-images.githubusercontent.com/277773/110137411-1f32ec80-7dd1-11eb-8b50-ff8f761455a5.mp4

This PR proposes the following and allows to have toggle‑all interactions that are not limited to the import.

https://user-images.githubusercontent.com/277773/110137488-340f8000-7dd1-11eb-8427-462cfee1792b.mp4

- Rename classes and function to something more descriptive.
- Use specific DOM targets instead of relying on the DOM ancestor tree.
- [a11y] Listen to the element checked status instead of a click on a non‑focusable element.
- [a11y] Add a skip‑link at the top of the list jumping to the end of the list and avoid tabbing through all failed items.
- [a11y] Avoid having the label on the whole width to prevent accidental click.
- [html] Move `fieldset` out of `ul`.
- Update related i18n strings in French.

2021-03-05 15:55 UTC, arkhi commented
I realise there is no explanation for the videos.

Currently, after importing books, the import page shows two sections:

1. Failed imports.
2. Successful imports.

_Failed imports_ lists all books with a checkbox to select those we want to try importing again and a “Select all” checkbox. Tabbing to “Select all” is impossible for a couple of reasons though:

- The element on which the click is listened to is not focusable, ergo not reachable (correct me if I’m wrong).
- This means the checkboxes statuses depend on a stateless element, which makes it harder to handle. As a consequence, there is no _unchecking all_ failed imports.

This PR listens to the main “Select all” checkbox status triggered by the browser handled’s logic (<kbd>space</kbd> to (un)check, click on the label, etc.).

2021-03-05 17:49 UTC, Flameborn commented
Thanks for this, the skip link is very much appreciated, though at the moment there is a heading that separates the failed and successful imports, so if this is visually an issue, it can be safely discarded.

Regarding the *select all* checkbox, I noticed that if I checked it (it could be focused via VoiceOver under Safari), the state changed, but the state of the checkboxes before it did not.

The tab key definitely did not work as it should have, so this is very nice to have as well.

2021-03-05 19:49 UTC, mouse-reeve commented
I'm having a little trouble with the skip link - I have an import with one item available for retry, and the skip link appears covering the item when I try to use the checkbox associated with it. Could the link just be a regular link that is always visible, rather than appearing and disappearing?

2021-03-05 20:11 UTC, Flameborn commented
Sure, a single skip link is fine. Since screen readers read linearly, it really doesn't matter what's visible or isn't, as long as it's there when it needs to be ☺️

Since there's a heading present for the successful imports, if the skip link's too much trouble, you can safely choose to not add it, as the heading can be navigated to and that essentially skips the list of checkboxes. The only one button *retry* is one key away when navigating backwards.

2021-03-05 20:38 UTC, arkhi commented
All of this makes sense. I’ll make and update.

2021-03-05 21:14 UTC, arkhi commented
The link will now only appear for everyone as a simple link at the top of the list if there is more than 10 failed imports; as a “sight-able” user, scrolling through the 70 failed imports I had really was not the best experience.

The number is totally arbitrary. :)

I also added smooth scrolling and a scroll padding to give more context when looking at the “select all” option.

Let me know. :)

2021-03-05 21:21 UTC, Flameborn commented
I wish I had 70 failed imports only, haha.

Sounds good to me.

2021-03-06 17:00 UTC, mouse-reeve requested changes
works great, thank you for fixing this

2021-03-06 20:20 UTC, arkhi commented on bookwyrm/static/css/format.css
> +}
Some CSS? Which CSS? Oh look… It’s gone!

(I think this could be used later on but you’re right; let’s not clutter with unused stuff _now_.)

2021-03-06 21:05 UTC, merged